# Generated by Django 4.0.5 on 2022-06-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend_request',
            name='accepted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
