# Generated by Django 4.0.5 on 2022-06-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_friend_request_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend_request',
            name='accepted',
        ),
        migrations.AddField(
            model_name='friend_list',
            name='is_friends',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
