# Generated by Django 4.0.5 on 2022-06-06 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=250)),
                ('phone', models.BigIntegerField()),
                ('mother_name', models.CharField(max_length=250)),
                ('father_name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=7)),
                ('religion', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('date_of_birth', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=250)),
                ('marital_status', models.CharField(max_length=50)),
                ('height', models.CharField(max_length=50)),
                ('weight', models.BigIntegerField(max_length=50)),
                ('body_type', models.CharField(max_length=50)),
                ('physical_status', models.CharField(max_length=50)),
                ('food', models.CharField(max_length=50)),
                ('smoking', models.CharField(max_length=50)),
                ('drinking', models.CharField(max_length=50)),
                ('profile', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('token', models.CharField(default=None, max_length=200, null=True)),
                ('gender', models.CharField(max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_info', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user_info')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
