# Generated by Django 4.0.5 on 2022-06-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_profile_views_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_views',
            name='visited_user',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
