# Generated by Django 4.0.5 on 2022-06-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_profile_views_visited_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='profile',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
    ]
